notifications:
  email: false

language: generic

# Node.js requires GCC 4.8.
sudo: required
dist: trusty

env: ROOTFS="$TRAVIS_BUILD_DIR/product/rootfs.tar.xz"

branches:
  except: /^product/

script:
  - ./nano build container
  - |
    while true; do sleep 60; echo Building...; done &
    ./nano build rootfs 2>~/error.log | tee ~/build.log | grep '^\S*>>>\s'
    kill $!
  - ./nano pull rootfs

  # Test rootfs readable.
  - '[[ -r $ROOTFS ]]'

  # Test rootfs begins with root entry.
  - '[[ $(tar tf "$ROOTFS" | head -1) = ./ ]]'

  # Test rootfs contains node and npm binaries.
  - (( $(tar tf "$ROOTFS" | grep -Fxce ./usr/bin/node -e ./usr/bin/npm) == 2 ))

after_failure:
  - tail -50 ~/error.log
  - tail -50 ~/build.log

after_success:
  # Decrypt Git credentials file.
  - |
    (
      for var in "${!encrypted_@}"; do
        [[ $var = *_key ]] && key=${!var}
        [[ $var = *_iv ]] && iv=${!var}
      done
      openssl aes-256-cbc -K "$key" -iv "$iv" -in .git-credentials.enc -out ~/.git-credentials -d
    )

  # Work in new directory.
  - mkdir -v newproduct && cd $_

  # Initialize and configure Git.
  - |
    git init
    git config user.name Travis
    git config user.email bilge+travis@scriptfusion.com
    git config credential.helper store
    git remote add origin https://github.com/"$TRAVIS_REPO_SLUG"

  # Pull the most recent commit.
  - git pull --depth=1 origin "${branch=product/"$TRAVIS_BRANCH"}"

  # Copy rootfs and product skeleton.
  - cp -fl ../product/* .

  # Push modified product files.
  - git add .;
    git commit -m "Built product from $TRAVIS_COMMIT." && git push origin HEAD:"$branch"
